//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P08R01MVC_Plagas_MDRE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plaga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plaga()
        {
            this.Prevencions = new HashSet<Prevencion>();
            this.Tratamientos = new HashSet<Tratamiento>();
        }
    
        public int IdPlaga { get; set; }
        public string NombreComun { get; set; }
        public string NombreCientifico { get; set; }
        public string Categoria { get; set; }
        public string NivelRiesgo { get; set; }
        public string UrlImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prevencion> Prevencions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamiento> Tratamientos { get; set; }
    }
}
