//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P08R01MVC_Plagas_MDRE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento
    {
        public int IdTratamiento { get; set; }
        public Nullable<int> IdPlaga { get; set; }
        public string Tipo { get; set; }
        public string NombreProducto { get; set; }
        public string Instrucciones { get; set; }
    
        public virtual Plaga Plaga { get; set; }
    }
}
